// TODO: This file will be generated by FlutterFire CLI
// Run: flutterfire configure
//
// This is a placeholder. After running flutter create and flutterfire configure,
// this file will be replaced with your actual Firebase configuration.

// ignore_for_file: avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHx1bhoKsGkr9MEoO-LrKGx1gfcKuhDHU',
    appId: '1:503244947942:android:586db84b603383816a1627',
    messagingSenderId: '503244947942',
    projectId: 'remotealarm-be4d7',
    storageBucket: 'remotealarm-be4d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTL2V3bKRI0Qfrl1m8kZl-K182yZWCvLU',
    appId: '1:503244947942:ios:1c2586688fd184fa6a1627',
    messagingSenderId: '503244947942',
    projectId: 'remotealarm-be4d7',
    storageBucket: 'remotealarm-be4d7.firebasestorage.app',
    iosClientId: '503244947942-ogqqqh48losan3th9c3ua7vp8vm3g00f.apps.googleusercontent.com',
    iosBundleId: 'com.remotealarm',
  );

}